### ISSUE TITLE
Nur Medics dürfen Heilen

### ISSUE THREAD

**Issue by GSG-Alcedo** [Grenzschutzgruppe/gsg_gm_liberation#14]
**Describe the bug**
alle können heilen

**To Reproduce**
join
get injured
fix yourself

**Expected behavior**
picturelichkeit

**Screenshots**
never happen!

**Desktop (please complete the following information):**
error 404

**Smartphone (please complete the following information):**
 Fuck off

**Additional context**
mach mal!

**Comment by GSG-Alcedo** [comment]
Medics brauchen ACE-Medic proc!

**Comment by Pictureclass** [comment]
Medic Prog ist da, geht trotzdem nicht :(

**Comment by Pictureclass** [comment]
Das PAK ist nur für Advanced Medic gedacht
