### ISSUE TITLE
Supplies nicht verladbar

### ISSUE THREAD

**Issue by trenchfries** [Grenzschutzgruppe/gsg_gm_liberation#26]

**Comment by Pictureclass** [comment]
Per ACE oder mit Mausradmenu?

**Comment by Pictureclass** [comment]
`11:38:34 Error in expression <
_truck_to_load = _next_truck;
_ammobox attachTo [ _truck_to_load, _offsets sele>
11:38:34   Error position: <attachTo [ _truck_to_load, _offsets sele>
11:38:34   Error 2 Elemente angegeben, 3 erwartet
11:38:34 File mpmissions\__CUR_MP.gm_weferlingen_summer\scripts\client\ammoboxes\do_load_box.sqf, line 24`
